spring.application.name=employee-performance
# Default active profile if none specified
spring.profiles.active=dev

# Sring Docs Api Path
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Sort endpoints alphabetically by HTTP Method
springdoc.swagger-ui.operationsSorter=alpha